<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE networks [
	<!ELEMENT networks (network*)>
		<!ELEMENT network (name?, description?, addresses, profiles?,
		                   channels?, commands?)>
			<!ATTLIST network id ID #REQUIRED
							  autoconnect (yes|no) #IMPLIED
							  workerthreads CDATA #IMPLIED
							  proxy CDATA #IMPLIED>
			<!ELEMENT name (#PCDATA)>
			<!ELEMENT description (#PCDATA)>
			<!ELEMENT addresses (address+)>
				<!ATTLIST addresses randomorder (yes|no) #IMPLIED>
				<!ELEMENT address (url, port)>
					<!ATTLIST address secure (yes|no) #IMPLIED
					                  proxy CDATA #IMPLIED>
					<!ELEMENT url (#PCDATA)>
					<!ELEMENT port (#PCDATA)>
			<!ELEMENT profiles (profile*)>
				<!ATTLIST profiles useall (yes|no) #REQUIRED>
				<!ELEMENT profile (#PCDATA)>
			<!ELEMENT channels (channel*)>
				<!ELEMENT channel (#PCDATA)>
]>
<networks>
	<network id="synirc" autoconnect="no">
		<name>synIRC</name>
		<addresses randomorder="no">
			<address secure="yes">
				<url>irc.synirc.org</url>
				<port>7001</port>
			</address>
			<address>
				<url>irc.synirc.net</url>
				<port>6667</port>
			</address>
		</addresses>
	</network>
</networks>
